---
#Playbook para crear usuarios en Linux by Jonnathan López
- name: Creación de usuario en hosts remotos
  hosts: fedora #Modificar fedora por el listado de hosts en el archivo /etc/ansible/hosts.
  tasks:
    - name: Creando el usuario
      user:
        name: james #Modificar james por el usuario a crear
        comment: comentario #Comentario para el usuario
        uid: 3000 #Modificar 3000 por el uid que tendrá el usuario nuevo
        group: jboss #Modificar jboss por el grupo donde estara el usuario, previamente creado el grupo
        shell: /bin/bash #Si requiere /bin/bash
        home: /home/usuario #Modificar el home del nuevo usuario
        state: present
          


   
